
// afbeeldingen vervangen met placeholders

import placeholder1 from "../assets/placeholder-imgs/drink_icons001-01_g172.png";
import placeholder2 from "../assets/placeholder-imgs/drink_icons001-01_g234.png";
import placeholder3 from "../assets/placeholder-imgs/drink_icons001-01_g335.png";
import placeholder4 from "../assets/placeholder-imgs/drink_icons001-01_g419.png";
import placeholder5 from "../assets/placeholder-imgs/drink_icons001-01_g562.png";
import placeholder6 from "../assets/placeholder-imgs/drink_icons001-01_g628.png";
import placeholder7 from "../assets/placeholder-imgs/drink_icons001-01_g75.png";

// https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a

export const testCocktails = [
  {
    idDrink: "17222",
    strDrink: "A1",
    strCategory: "Cocktail",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions: "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
    strDrinkThumb: placeholder1,
    strIngredient1: "Gin",
    strIngredient2: "Grand Marnier",
    strIngredient3: "Lemon Juice",
    strIngredient4: "Grenadine",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 3/4 shot ",
    strMeasure2: "1 Shot ",
    strMeasure3: "1/4 Shot",
    strMeasure4: "1/8 Shot",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
  {
    idDrink: "13501",
    strDrink: "ABC",
    strCategory: "Shot",
    strAlcoholic: "Alcoholic",
    strGlass: "Shot glass",
    strInstructions: "Layered in a shot glass.",
    strDrinkThumb: placeholder2,
    strIngredient1: "Amaretto",
    strIngredient2: "Baileys irish cream",
    strIngredient3: "Cognac",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/3 ",
    strMeasure2: "1/3 ",
    strMeasure3: "1/3 ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
  {
    idDrink: "17225",
    strDrink: "Ace",
    strCategory: "Cocktail",
    strAlcoholic: "Alcoholic",
    strGlass: "Martini Glass",
    strInstructions: "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
    strDrinkThumb: placeholder3,
    strIngredient1: "Gin",
    strIngredient2: "Grenadine",
    strIngredient3: "Heavy cream",
    strIngredient4: "Milk",
    strIngredient5: "Egg White",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 shots ",
    strMeasure2: "1/2 shot ",
    strMeasure3: "1/2 shot ",
    strMeasure4: "1/2 shot",
    strMeasure5: "1/2 Fresh",
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
  {
    idDrink: "14610",
    strDrink: "ACID",
    strCategory: "Shot",
    strAlcoholic: "Alcoholic",
    strGlass: "Shot glass",
    strInstructions: "Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.",
    strDrinkThumb: placeholder4,
    strIngredient1: "151 proof rum",
    strIngredient2: "Wild Turkey",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz Bacardi ",
    strMeasure2: "1 oz ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
  {
    idDrink: "13938",
    strDrink: "AT&T",
    strCategory: "Ordinary Drink",
    strAlcoholic: "Alcoholic",
    strGlass: "Highball Glass",
    strInstructions: "Pour Vodka and Gin over ice, add Tonic and Stir",
    strDrinkThumb: placeholder5,
    strIngredient1: "Absolut Vodka",
    strIngredient2: "Gin",
    strIngredient3: "Tonic water",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "4 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
  {
    idDrink: "17837",
    strDrink: "Adam",
    strCategory: "Ordinary Drink",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions: "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
    strDrinkThumb: placeholder6,
    strIngredient1: "Dark rum",
    strIngredient2: "Lemon juice",
    strIngredient3: "Grenadine",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "1 tsp ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
  {
    idDrink: "17833",
    strDrink: "A. J.",
    strCategory: "Ordinary Drink",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions: "Shake ingredients with ice, strain into a cocktail glass, and serve.",
    strDrinkThumb: placeholder7,
    strIngredient1: "Applejack",
    strIngredient2: "Grapefruit juice",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
  },
];
